language: node_js

node_js:
  - 'node'
  - 'lts/*'

addons:
    code_climate:
        repo_token: 17ec5d4e6aec2a05d8edffba4a4aed77cdec42194c4a7499c57d92541379699a
script:
  - npm run istanbul
  - npm run build

before_script:
  - npm install codeclimate-test-reporter istanbul -g

after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0

cache:
  directories:
    - node_modules
